generate-db:
	sqlboiler mysql

regenerate-db:
	rm -rf pkg/models_autogenerated
	sqlboiler mysql

run-docker:
	docker container rm blog-db -f
	docker-compose -f  docker-compose.yml down --remove-orphans --volumes
	docker-compose up --force-recreate --build