package logic

import (
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models"
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models_autogenerated"
)

func (h *Handler) Create(article models.Article) (*models.ArticleId, error) {
	return h.store.Create(article)
}

func (h *Handler) Read(id int) (*models_autogenerated.ArticleSlice, error) {
	return h.store.Read(id)
}
