package logic

import (
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models"
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models_autogenerated"
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/store"
)

type Logic interface {
	AdminStore
}

type AdminStore interface {
	Create(article models.Article) (*models.ArticleId, error)
	Read(id int) (*models_autogenerated.ArticleSlice, error)
}

type Handler struct {
	store store.Store
}

func NewLogicHandler(store store.Store) Logic {
	return &Handler{
		store: store,
	}
}
