package store

import (
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models"
	"github.com/juddbaguio/blog-exam-repo-recreate/pkg/models_autogenerated"
)

type Store interface {
	AdminStore
}

type AdminStore interface {
	Create(article models.Article) (*models.ArticleId, error)
	Read(id int) (*models_autogenerated.ArticleSlice, error)
}
